import Image from "next/image";
import { ArrowDownRight, ArrowUpRight, Camera, Star } from "lucide-react";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { ProductCard } from "@/components/ProductCard";
import { SectionTitle } from "@/components/SectionTitle";
import { WhatsAppButton } from "@/components/WhatsAppButton";
import { company } from "@/config/company";
import { getCatalog } from "@/lib/catalog";

export default async function Home() {
  const { categories, products } = await getCatalog();
  const featured = products.filter((product) => product.featured);
  const bestSellers = products.filter((product) => product.bestSeller);

  return <><Header /><main id="inicio">
    <section className="hero-grid relative flex min-h-[720px] items-end overflow-hidden bg-[#171313] pt-28"><Image src="https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=1800&q=85" alt="Hambúrguer artesanal Elite Burger House" fill priority sizes="100vw" className="object-cover object-center opacity-55" /><div className="absolute inset-0 bg-gradient-to-r from-[#0c0b0b] via-[#0c0b0b]/75 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-[#0c0b0b] via-transparent to-[#0c0b0b]/30" /><div className="relative mx-auto w-full max-w-7xl px-5 pb-24 lg:px-8"><p className="mb-5 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.3em] text-[#f0b849]"><span className="h-px w-8 bg-[#f0b849]" />Artesanal de verdade</p><h1 className="max-w-3xl font-display text-7xl uppercase leading-[0.82] text-white sm:text-8xl md:text-[9rem]">Elite <span className="text-[#e33b32]">Burger</span><br />House</h1><p className="mt-7 max-w-md text-lg text-white/70">Seu hambúrguer do jeito que você gosta.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#cardapio" className="inline-flex items-center justify-center gap-2 rounded-full bg-[#f0b849] px-6 py-3.5 text-sm font-black uppercase text-[#171313] transition hover:bg-white">Ver cardápio <ArrowDownRight size={17} /></a><WhatsAppButton /></div></div></section>
    <section id="cardapio" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-8 md:flex-row md:items-end"><SectionTitle eyebrow="Feito na chapa, servido com atitude" title="Cardápio" description="Ingredientes selecionados, blends suculentos e combinações que fazem cada mordida valer a pena." /><a href="#destaques" className="flex items-center gap-2 text-sm font-bold uppercase text-[#f0b849] hover:text-white">Ver destaques <ArrowUpRight size={18} /></a></div>{products.length === 0 ? <EmptyCatalog /> : <div className="mt-12 space-y-16">{categories.map((category) => { const categoryProducts = products.filter((product) => product.category.id === category.id); return categoryProducts.length > 0 ? <section key={category.id} aria-labelledby={`category-${category.id}`}><div className="mb-6 flex items-center gap-3"><h3 id={`category-${category.id}`} className="font-display text-3xl uppercase text-white">{category.name}</h3><span className="h-px flex-1 bg-white/10" /></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{categoryProducts.map((product) => <ProductCard key={product.id} {...product} tag={product.bestSeller ? "Mais vendido" : product.featured ? "Destaque" : undefined} />)}</div></section> : null; })}</div>}</section>
    <section id="destaques" className="border-y border-white/10 bg-[#171313] px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><SectionTitle eyebrow="Escolhas da casa" title="Em destaque" />{featured.length === 0 ? <EmptyCatalog compact /> : <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{featured.map((product) => <ProductCard key={product.id} {...product} tag="Destaque" />)}</div>}<div className="mt-16"><SectionTitle eyebrow="Os favoritos" title="Mais vendidos" />{bestSellers.length === 0 ? <EmptyCatalog compact /> : <div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{bestSellers.map((product) => <ProductCard key={product.id} {...product} tag="Mais vendido" />)}</div>}</div></div></section>
    <section className="relative overflow-hidden px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 md:grid-cols-2"><div><SectionTitle eyebrow="A nossa história" title="Feito para quem leva sabor a sério" description="Na Elite, acreditamos que um burger memorável começa com ingredientes de verdade e termina com aquele silêncio da primeira mordida. Tudo é preparado na hora, com cuidado e personalidade." /><div className="mt-8 flex items-center gap-6"><div className="flex gap-1 text-[#f0b849]"><Star fill="currentColor" size={16} /><Star fill="currentColor" size={16} /><Star fill="currentColor" size={16} /><Star fill="currentColor" size={16} /><Star fill="currentColor" size={16} /></div><span className="text-sm text-white/50">Sabor que deixa marca</span></div></div><div className="relative aspect-square overflow-hidden rounded-2xl"><Image src="https://images.unsplash.com/photo-1550317138-10000687a72b?auto=format&fit=crop&w=1000&q=85" alt="Burger artesanal sendo preparado" fill sizes="(max-width: 768px) 92vw, 45vw" className="object-cover" /></div></div></section>
    <section className="bg-[#d9342b] px-5 py-20 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.28em] text-white/70">Bateu a fome?</p><h2 className="mt-3 font-display text-5xl uppercase leading-none text-white md:text-7xl">O próximo burger<br />é por nossa conta.</h2></div><WhatsAppButton /></div></section>
    <section className="px-5 py-24 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><SectionTitle eyebrow="Siga o cheiro" title="A Elite no Instagram" description={`Acompanhe ${company.instagram} e fique por dentro das novidades.`} /><a href={company.instagramUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-bold text-[#f0b849] hover:text-white"><Camera size={18} /> @{company.instagram}</a></div></section>
  </main><Footer /></>;
}

function EmptyCatalog({ compact = false }: { compact?: boolean }) { return <div className={`${compact ? "py-12" : "py-20"} text-center`}><p className="font-display text-2xl uppercase text-white/70">Cardápio em atualização</p><p className="mt-2 text-sm text-white/40">Nenhum produto disponível no momento.</p></div>; }
