"use client";

import Image from "next/image";
import { Check, Plus, X } from "lucide-react";
import { useState } from "react";
import { useCart } from "@/components/CartProvider";

type ProductCardProps = { id: string; name: string; description: string; ingredients: string; price: string; promotionalPrice: string | null; image: string | null; available: boolean; tag?: string };

export function ProductCard({ id, name, description, ingredients, price, promotionalPrice, image, available, tag }: ProductCardProps) {
  const [open, setOpen] = useState(false);
  const displayPrice = promotionalPrice ?? price;
  return <><article className={`group overflow-hidden rounded-2xl border border-white/10 bg-[#171313] transition hover:-translate-y-1 hover:border-[#e33b32]/50 ${!available ? "opacity-75" : ""}`}><div className="relative aspect-[1.15] overflow-hidden">{image ? <Image src={image} alt={name} fill sizes="(max-width: 768px) 92vw, 30vw" className="object-cover transition duration-700 group-hover:scale-105" /> : <div className="h-full bg-[#241f1f]" />}{tag && <span className="absolute left-4 top-4 rounded-full bg-[#d9342b] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{tag}</span>}{!available && <span className="absolute right-4 top-4 rounded-full bg-[#171313]/90 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Indisponível</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="font-display text-2xl font-black uppercase text-white">{name}</h3><div className="text-right"><strong className="whitespace-nowrap text-sm text-[#f0b849]">{displayPrice}</strong>{promotionalPrice && <del className="block text-xs text-white/35">{price}</del>}</div></div><p className="mt-2 min-h-12 text-sm leading-6 text-white/55">{description}</p><button disabled={!available} onClick={() => setOpen(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-white/15 py-3 text-xs font-bold uppercase tracking-wider text-white transition hover:border-[#e33b32] hover:bg-[#e33b32] disabled:cursor-not-allowed disabled:border-white/10 disabled:text-white/30"><Plus size={16} /> {available ? "Adicionar ao pedido" : "Indisponível"}</button></div></article>{open && <ProductDetail id={id} name={name} description={description} ingredients={ingredients} price={displayPrice} image={image} onClose={() => setOpen(false)} />}</>;
}

function ProductDetail({ id, name, description, ingredients, price, image, onClose }: { id: string; name: string; description: string; ingredients: string; price: string; image: string | null; onClose: () => void }) { const [quantity, setQuantity] = useState(1); const { addItem } = useCart(); return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 sm:items-center sm:p-5"><div className="relative max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-[#171313] sm:rounded-2xl"><button onClick={onClose} aria-label="Fechar detalhes" className="absolute right-4 top-4 z-10 rounded-full bg-black/50 p-2 text-white"><X size={18} /></button><div className="relative aspect-[1.8]">{image ? <Image src={image} alt={name} fill sizes="(max-width: 768px) 100vw, 672px" className="object-cover" /> : <div className="h-full bg-[#241f1f]" />}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.25em] text-[#f0b849]">Detalhes do produto</p><h2 className="mt-2 font-display text-4xl uppercase text-white">{name}</h2><p className="mt-3 text-sm leading-6 text-white/60">{description}</p><p className="mt-4 flex items-start gap-2 text-sm text-white/70"><Check size={17} className="mt-0.5 shrink-0 text-[#f0b849]" />{ingredients}</p><div className="mt-7 flex items-center justify-between gap-4"><div className="flex items-center gap-3 rounded-xl border border-white/15 p-1"><button onClick={() => setQuantity(Math.max(1, quantity - 1))} className="h-9 w-9 rounded-lg text-white hover:bg-white/10">-</button><span className="w-5 text-center font-bold text-white">{quantity}</span><button onClick={() => setQuantity(quantity + 1)} className="h-9 w-9 rounded-lg text-white hover:bg-white/10">+</button></div><button onClick={() => { addItem({ id, name, price, image }, quantity); onClose(); }} className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-[#e33b32] py-3 text-sm font-bold text-white hover:bg-[#c92d25]"><Plus size={17} /> Adicionar · R$ {(Number(price.replace("R$ ", "").replace(".", "").replace(",", ".")) * quantity).toFixed(2).replace(".", ",")}</button></div></div></div></div>; }